import { readFile } from 'node:fs/promises'
import { join, resolve } from 'node:path'
import { firstParagraph, renderMarkdown } from './markdown.ts'
import type { Heading, ImageSize } from './markdown.ts'

export type DocPage = { slug: string; title: string; description?: string }
/** A manifest page as synced: plus its last commit date and the images it shows (paths relative to docs/site). */
export type ManifestPage = DocPage & { lastModified?: string; images?: string[] }
export type DocSection = { title: string; pages: ManifestPage[] }
export type DocsManifest = { sections: DocSection[] }
export type DocNeighbours = { previous: DocPage | null; next: DocPage | null }
export type Doc = ManifestPage & { section: string; html: string; headings: Heading[]; description: string }

/** Generated by scripts/sync-docs.mjs; shipped next to the built app. */
export function contentDir(): string { return resolve(/* turbopackIgnore: true */ process.env.CONTENT_DIR || join(process.cwd(), 'content')) }

const cache = new Map<string, Promise<unknown>>()
/** Reads a generated content file; cached in production, re-read in development. */
export function readContent<T>(name: string, parse: (raw: string) => T): Promise<T> {
  const path = join(contentDir(), name)
  const load = () => readFile(/* turbopackIgnore: true */ path, 'utf8').then(parse, (error: NodeJS.ErrnoException) => {
    if (error.code === 'ENOENT') throw new Error(`Missing ${path}. Run "node scripts/sync-docs.mjs" from the repository root before building or starting the website.`)
    throw error
  })
  if (process.env.NODE_ENV !== 'production') return load()
  if (!cache.has(path)) cache.set(path, load().catch(error => { cache.delete(path); throw error }))
  return cache.get(path) as Promise<T>
}

export function parseManifest(raw: string): DocsManifest {
  const data = JSON.parse(raw) as DocsManifest
  if (!Array.isArray(data.sections)) throw new Error('content/manifest.json has no sections')
  return { sections: data.sections.map(s => ({ title: s.title, pages: s.pages.map(p => ({
    slug: p.slug, title: p.title,
    ...(p.description ? { description: p.description } : {}),
    ...(p.lastModified ? { lastModified: p.lastModified } : {}),
    ...(p.images?.length ? { images: p.images } : {}),
  })) })) }
}
export function loadManifest(): Promise<DocsManifest> { return readContent('manifest.json', parseManifest) }
/** Width and height of each docs image (content/images.json, written by scripts/sync-docs.mjs). */
export function loadImageSizes(): Promise<Record<string, ImageSize>> { return readContent('images.json', raw => JSON.parse(raw) as Record<string, ImageSize>) }

export function allPages(manifest: DocsManifest): (ManifestPage & { section: string })[] {
  return manifest.sections.flatMap(section => section.pages.map(page => ({ ...page, section: section.title })))
}
export function findPage(manifest: DocsManifest, slug: string): (ManifestPage & { section: string }) | null {
  return allPages(manifest).find(page => page.slug === slug) ?? null
}
/** Previous / next page in reading order across sections; both null for an unknown slug. */
export function neighbours(manifest: DocsManifest, slug: string): DocNeighbours {
  const pages = allPages(manifest), i = pages.findIndex(page => page.slug === slug)
  if (i < 0) return { previous: null, next: null }
  const strip = (p: (ManifestPage & { section: string }) | undefined): DocPage | null => p ? { slug: p.slug, title: p.title, ...(p.description ? { description: p.description } : {}) } : null
  return { previous: strip(pages[i - 1]), next: strip(pages[i + 1]) }
}

const SLUG = /^[a-z0-9]+(?:-[a-z0-9]+)*$/
/** Loads and renders one docs page, or null when the slug is unknown. */
export async function loadDoc(slug: string): Promise<Doc | null> {
  if (!SLUG.test(slug)) return null
  const manifest = await loadManifest(), page = findPage(manifest, slug)
  if (!page) return null
  const [source, images] = await Promise.all([readContent(`docs/${slug}.md`, raw => raw), loadImageSizes()])
  const { html, headings } = renderMarkdown(source, { docSlugs: new Set(allPages(manifest).map(p => p.slug)), stripTitle: true, images })
  return { ...page, html, headings, description: page.description || firstParagraph(source.replace(/^#[^\n]*\n/, '')) }
}
