#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.."
mkdir -p .deploy
# content/ is generated by scripts/sync-docs.mjs (docs, release notes, NOTICE); the server has no repository checkout.
test -f app/webapp/content/manifest.json || { echo 'app/webapp/content is missing: run node scripts/sync-docs.mjs before building.' >&2; exit 1; }
tar -czf .deploy/webapp.tar.gz --exclude='.next/cache' --exclude='.next/types' --exclude='.next/dev' -C app/webapp package.json package-lock.json next.config.ts tsconfig.json next-env.d.ts public public-key.pem src content .next
echo 'Website archive ready: .deploy/webapp.tar.gz'
