import appIconUrl from '@/assets/app-icon.png'
import { cn } from '@/lib/utils'

/**
 * The app mark (64 px raster of build/icons/icon.svg, regenerated by `node scripts/make-icons.mjs`).
 * Decorative: the product name is always printed next to it.
 */
export function AppIcon({ size = 28, className }: { size?: number; className?: string }): React.JSX.Element {
  return <img src={appIconUrl} width={size} height={size} alt="" aria-hidden="true" draggable={false} className={cn('shrink-0 select-none', className)} />
}
