'use client'
import { useState } from 'react'
import type { Release } from '@/lib/releases'
const MAC_ARCH_LABELS = { arm64: 'Apple silicon', x64: 'Intel' } as const
/** macOS card, rendered only for releases that carry macOS downloads (DMG preferred over ZIP per architecture). */
function MacDownloads({ release }: { release: Release }) {
  const downloads = (['arm64', 'x64'] as const).map(arch => { const files = (release.macAssets ?? []).filter(a => a.arch === arch); return files.find(a => a.fileName.endsWith('.dmg')) ?? files[0] }).filter(a => a !== undefined)
  return <article className="download-card"><div className="platform-mark" aria-hidden="true"><svg viewBox="0 0 24 24" width="32" height="32"><path fill="currentColor" d="M16.4 12.6c0-2.3 1.9-3.4 2-3.5-1.1-1.6-2.8-1.8-3.4-1.8-1.4-.2-2.8.8-3.5.8s-1.8-.8-3-.8C6.9 7.3 5.4 8.2 4.6 9.7c-1.7 2.9-.4 7.2 1.2 9.6.8 1.2 1.7 2.4 3 2.4 1.2 0 1.6-.8 3.1-.8 1.4 0 1.8.8 3.1.8s2.1-1.2 2.9-2.3c.9-1.3 1.3-2.6 1.3-2.7 0 0-2.8-1-2.8-4.1zM14.1 5.6c.6-.8 1.1-1.9 1-3-1 0-2.1.7-2.8 1.5-.6.7-1.1 1.8-1 2.9 1.1.1 2.1-.6 2.8-1.4z"/></svg></div><span className="tag">macOS 12 OR LATER · UNSIGNED</span><h3>macOS</h3><p>Open the disk image and drag the app into Applications. Download new versions here and replace the app; your profiles stay on your Mac.</p><details className="mac-first-open"><summary>First launch: this build is not notarized by Apple</summary><p>The Mac build is free and not yet signed with an Apple Developer ID, so macOS blocks it the first time. To open it once:</p><ol><li>Open <strong>Proxy-QA-Browser</strong> from Applications and close the warning.</li><li>Open <strong>System Settings → Privacy &amp; Security</strong>.</li><li>Scroll to the message about Proxy-QA-Browser and click <strong>Open Anyway</strong>, then confirm with your password.</li></ol><p>macOS remembers this; later launches open normally. Verify the SHA-256 checksum below if you want to be sure the download is intact. <a href="/docs/install#macos">Install guide</a></p></details>{downloads.map(asset => <div key={asset.fileName}><a className="button primary" href={`/api/download/${release.version}/${asset.fileName}`}>Download for {MAC_ARCH_LABELS[asset.arch]} <span aria-hidden="true">↓</span></a><p className="file-meta">v{release.version} · {(asset.size / 1024 ** 2).toFixed(1)} MB · {asset.fileName.endsWith('.dmg') ? '.dmg' : '.zip'}</p><details><summary>Verify SHA-256 checksum</summary><code className="checksum">{asset.sha256}</code></details></div>)}</article>
}
export default function Downloads({ initialRelease }: { initialRelease: Release | null }) {
  const [release, setRelease] = useState(initialRelease), [checking, setChecking] = useState(false), [message, setMessage] = useState('')
  async function check() {
    setChecking(true); setMessage('')
    try { const response = await fetch('/api/releases', { cache: 'no-store' }); if (!response.ok) throw new Error('Release information is temporarily unavailable.'); const result = await response.json() as { release: Release | null }; setRelease(result.release); setMessage(result.release ? `Latest release: ${result.release.version}. Your desktop app can check and download verified updates in App & updates.` : 'The first release is being prepared. Check back soon.') }
    catch (e) { setMessage(e instanceof Error ? e.message : 'Could not check for updates.') } finally { setChecking(false) }
  }
  return <section id="download" className="downloads section"><div className="section-heading"><div><span className="eyebrow">YOUR NEXT WORKSPACE</span><h2>One download.<br />A better place to test.</h2></div><p>Choose your operating system. Your profiles and proxy credentials stay on your device.</p></div><div className="download-grid">{(['win32', 'linux'] as const).map(platform => {
    const asset = release?.assets.find(a => a.platform === platform)
    return <article className="download-card" key={platform}><div className="platform-mark" aria-hidden="true">{platform === 'win32' ? <svg viewBox="0 0 24 24" width="32" height="32"><path fill="currentColor" d="M2 4l8-1v8H2zm10-1.3L22 1v10H12zM2 13h8v8l-8-1zm10 0h10v10l-10-1.7z" /></svg> : <svg viewBox="0 0 24 24" width="32" height="32"><path fill="currentColor" d="M8 8V6a4 4 0 018 0v2l3 8-2 4H7l-2-4z"/><ellipse cx="12" cy="15" rx="4" ry="5" fill="#f1f2fa"/><circle cx="10.5" cy="6" r=".7" fill="white"/><circle cx="13.5" cy="6" r=".7" fill="white"/><path fill="#6bd2a9" d="M10 8h4l-2 2zM4 21l4-3 2 4H4zm16 0-4-3-2 4h6z"/></svg>}</div><span className="tag">64-BIT DESKTOP</span><h3>{platform === 'win32' ? 'Windows' : 'Linux'}</h3><p>{platform === 'win32' ? 'A single EXE. Open it, complete first-run setup, and add your desktop or Start menu shortcut.' : 'A portable AppImage with bundled browsers. Make it executable and open it to get started.'}</p>{asset && release ? <><a className="button primary" href={`/api/download/${release.version}/${asset.fileName}`}>Download for {platform === 'win32' ? 'Windows' : 'Linux'} <span aria-hidden="true">↓</span></a><p className="file-meta">v{release.version} · {(asset.size / 1024 ** 2).toFixed(1)} MB · {platform === 'win32' ? '.exe' : '.AppImage'}</p><details><summary>Verify SHA-256 checksum</summary><code className="checksum">{asset.sha256}</code></details></> : <><button className="button" disabled>Release coming soon</button><p className="file-meta">Download appears after a verified release is published.</p></>}</article>
  })}{release?.macAssets?.length ? <MacDownloads release={release} /> : null}</div><div className="update-line"><span><span className="status-dot" /> {release ? `Published ${new Date(release.releasedAt).toLocaleDateString('en-GB', { timeZone: 'UTC' })}` : 'Preparing the first public release'}</span><button className="text-button" disabled={checking} onClick={check}>{checking ? 'Checking…' : 'Check for updates'} <span aria-hidden="true">↻</span></button></div><p className="feedback" role="status">{message}</p>{release && <details className="release-notes"><summary>What’s new in v{release.version}</summary><ul>{release.notes.map(note => <li key={note}>{note}</li>)}</ul></details>}</section>
}
